-- © 2001-2003 Peter Thiemann
-- this file is generated -- do not edit
module WASH.HTML.HTMLMonad 
  (module WASH.HTML.HTMLMonad,module WASH.HTML.HTMLMonadBase) 
  where
import Prelude hiding (div,head,map,span)
import WASH.HTML.HTMLMonadBase
-- end fixed prologue
a   = mkElement   "a"
a, a_S, a_T :: Monad m => HTMLCons x y m a
a_S = mkElement_S "a"
a_T = mkElement_T "a"
abbr   = mkElement   "abbr"
abbr, abbr_S, abbr_T :: Monad m => HTMLCons x y m a
abbr_S = mkElement_S "abbr"
abbr_T = mkElement_T "abbr"
acronym   = mkElement   "acronym"
acronym, acronym_S, acronym_T :: Monad m => HTMLCons x y m a
acronym_S = mkElement_S "acronym"
acronym_T = mkElement_T "acronym"
address   = mkElement   "address"
address, address_S, address_T :: Monad m => HTMLCons x y m a
address_S = mkElement_S "address"
address_T = mkElement_T "address"
applet   = mkElement   "applet"
applet, applet_S, applet_T :: Monad m => HTMLCons x y m a
applet_S = mkElement_S "applet"
applet_T = mkElement_T "applet"
area   = mkEmpty   "area"
area, area_S, area_T :: Monad m => HTMLCons x y m a
area_S = mkEmpty_S "area"
area_T = mkEmpty_T "area"
b   = mkElement   "b"
b, b_S, b_T :: Monad m => HTMLCons x y m a
b_S = mkElement_S "b"
b_T = mkElement_T "b"
base   = mkEmpty   "base"
base, base_S, base_T :: Monad m => HTMLCons x y m a
base_S = mkEmpty_S "base"
base_T = mkEmpty_T "base"
basefont   = mkEmpty   "basefont"
basefont, basefont_S, basefont_T :: Monad m => HTMLCons x y m a
basefont_S = mkEmpty_S "basefont"
basefont_T = mkEmpty_T "basefont"
bdo   = mkElement   "bdo"
bdo, bdo_S, bdo_T :: Monad m => HTMLCons x y m a
bdo_S = mkElement_S "bdo"
bdo_T = mkElement_T "bdo"
big   = mkElement   "big"
big, big_S, big_T :: Monad m => HTMLCons x y m a
big_S = mkElement_S "big"
big_T = mkElement_T "big"
blockquote   = mkElement   "blockquote"
blockquote, blockquote_S, blockquote_T :: Monad m => HTMLCons x y m a
blockquote_S = mkElement_S "blockquote"
blockquote_T = mkElement_T "blockquote"
body   = mkElement   "body"
body, body_S, body_T :: Monad m => HTMLCons x y m a
body_S = mkElement_S "body"
body_T = mkElement_T "body"
br   = mkEmpty   "br"
br, br_S, br_T :: Monad m => HTMLCons x y m a
br_S = mkEmpty_S "br"
br_T = mkEmpty_T "br"
button   = mkElement   "button"
button, button_S, button_T :: Monad m => HTMLCons x y m a
button_S = mkElement_S "button"
button_T = mkElement_T "button"
caption   = mkElement   "caption"
caption, caption_S, caption_T :: Monad m => HTMLCons x y m a
caption_S = mkElement_S "caption"
caption_T = mkElement_T "caption"
center   = mkElement   "center"
center, center_S, center_T :: Monad m => HTMLCons x y m a
center_S = mkElement_S "center"
center_T = mkElement_T "center"
cite   = mkElement   "cite"
cite, cite_S, cite_T :: Monad m => HTMLCons x y m a
cite_S = mkElement_S "cite"
cite_T = mkElement_T "cite"
code   = mkElement   "code"
code, code_S, code_T :: Monad m => HTMLCons x y m a
code_S = mkElement_S "code"
code_T = mkElement_T "code"
col   = mkEmpty   "col"
col, col_S, col_T :: Monad m => HTMLCons x y m a
col_S = mkEmpty_S "col"
col_T = mkEmpty_T "col"
colgroup   = mkElement   "colgroup"
colgroup, colgroup_S, colgroup_T :: Monad m => HTMLCons x y m a
colgroup_S = mkElement_S "colgroup"
colgroup_T = mkElement_T "colgroup"
dd   = mkElement   "dd"
dd, dd_S, dd_T :: Monad m => HTMLCons x y m a
dd_S = mkElement_S "dd"
dd_T = mkElement_T "dd"
del   = mkElement   "del"
del, del_S, del_T :: Monad m => HTMLCons x y m a
del_S = mkElement_S "del"
del_T = mkElement_T "del"
dfn   = mkElement   "dfn"
dfn, dfn_S, dfn_T :: Monad m => HTMLCons x y m a
dfn_S = mkElement_S "dfn"
dfn_T = mkElement_T "dfn"
dir   = mkElement   "dir"
dir, dir_S, dir_T :: Monad m => HTMLCons x y m a
dir_S = mkElement_S "dir"
dir_T = mkElement_T "dir"
div   = mkElement   "div"
div, div_S, div_T :: Monad m => HTMLCons x y m a
div_S = mkElement_S "div"
div_T = mkElement_T "div"
dl   = mkElement   "dl"
dl, dl_S, dl_T :: Monad m => HTMLCons x y m a
dl_S = mkElement_S "dl"
dl_T = mkElement_T "dl"
dt   = mkElement   "dt"
dt, dt_S, dt_T :: Monad m => HTMLCons x y m a
dt_S = mkElement_S "dt"
dt_T = mkElement_T "dt"
em   = mkElement   "em"
em, em_S, em_T :: Monad m => HTMLCons x y m a
em_S = mkElement_S "em"
em_T = mkElement_T "em"
fieldset   = mkElement   "fieldset"
fieldset, fieldset_S, fieldset_T :: Monad m => HTMLCons x y m a
fieldset_S = mkElement_S "fieldset"
fieldset_T = mkElement_T "fieldset"
font   = mkElement   "font"
font, font_S, font_T :: Monad m => HTMLCons x y m a
font_S = mkElement_S "font"
font_T = mkElement_T "font"
form   = mkElement   "form"
form, form_S, form_T :: Monad m => HTMLCons x y m a
form_S = mkElement_S "form"
form_T = mkElement_T "form"
frame   = mkEmpty   "frame"
frame, frame_S, frame_T :: Monad m => HTMLCons x y m a
frame_S = mkEmpty_S "frame"
frame_T = mkEmpty_T "frame"
frameset   = mkElement   "frameset"
frameset, frameset_S, frameset_T :: Monad m => HTMLCons x y m a
frameset_S = mkElement_S "frameset"
frameset_T = mkElement_T "frameset"
h1   = mkElement   "h1"
h1, h1_S, h1_T :: Monad m => HTMLCons x y m a
h1_S = mkElement_S "h1"
h1_T = mkElement_T "h1"
h2   = mkElement   "h2"
h2, h2_S, h2_T :: Monad m => HTMLCons x y m a
h2_S = mkElement_S "h2"
h2_T = mkElement_T "h2"
h3   = mkElement   "h3"
h3, h3_S, h3_T :: Monad m => HTMLCons x y m a
h3_S = mkElement_S "h3"
h3_T = mkElement_T "h3"
h4   = mkElement   "h4"
h4, h4_S, h4_T :: Monad m => HTMLCons x y m a
h4_S = mkElement_S "h4"
h4_T = mkElement_T "h4"
h5   = mkElement   "h5"
h5, h5_S, h5_T :: Monad m => HTMLCons x y m a
h5_S = mkElement_S "h5"
h5_T = mkElement_T "h5"
h6   = mkElement   "h6"
h6, h6_S, h6_T :: Monad m => HTMLCons x y m a
h6_S = mkElement_S "h6"
h6_T = mkElement_T "h6"
head   = mkElement   "head"
head, head_S, head_T :: Monad m => HTMLCons x y m a
head_S = mkElement_S "head"
head_T = mkElement_T "head"
hr   = mkEmpty   "hr"
hr, hr_S, hr_T :: Monad m => HTMLCons x y m a
hr_S = mkEmpty_S "hr"
hr_T = mkEmpty_T "hr"
html   = mkElement   "html"
html, html_S, html_T :: Monad m => HTMLCons x y m a
html_S = mkElement_S "html"
html_T = mkElement_T "html"
i   = mkElement   "i"
i, i_S, i_T :: Monad m => HTMLCons x y m a
i_S = mkElement_S "i"
i_T = mkElement_T "i"
iframe   = mkElement   "iframe"
iframe, iframe_S, iframe_T :: Monad m => HTMLCons x y m a
iframe_S = mkElement_S "iframe"
iframe_T = mkElement_T "iframe"
img   = mkEmpty   "img"
img, img_S, img_T :: Monad m => HTMLCons x y m a
img_S = mkEmpty_S "img"
img_T = mkEmpty_T "img"
input   = mkEmpty   "input"
input, input_S, input_T :: Monad m => HTMLCons x y m a
input_S = mkEmpty_S "input"
input_T = mkEmpty_T "input"
ins   = mkElement   "ins"
ins, ins_S, ins_T :: Monad m => HTMLCons x y m a
ins_S = mkElement_S "ins"
ins_T = mkElement_T "ins"
isindex   = mkEmpty   "isindex"
isindex, isindex_S, isindex_T :: Monad m => HTMLCons x y m a
isindex_S = mkEmpty_S "isindex"
isindex_T = mkEmpty_T "isindex"
kbd   = mkElement   "kbd"
kbd, kbd_S, kbd_T :: Monad m => HTMLCons x y m a
kbd_S = mkElement_S "kbd"
kbd_T = mkElement_T "kbd"
label   = mkElement   "label"
label, label_S, label_T :: Monad m => HTMLCons x y m a
label_S = mkElement_S "label"
label_T = mkElement_T "label"
legend   = mkElement   "legend"
legend, legend_S, legend_T :: Monad m => HTMLCons x y m a
legend_S = mkElement_S "legend"
legend_T = mkElement_T "legend"
li   = mkElement   "li"
li, li_S, li_T :: Monad m => HTMLCons x y m a
li_S = mkElement_S "li"
li_T = mkElement_T "li"
link   = mkEmpty   "link"
link, link_S, link_T :: Monad m => HTMLCons x y m a
link_S = mkEmpty_S "link"
link_T = mkEmpty_T "link"
map   = mkElement   "map"
map, map_S, map_T :: Monad m => HTMLCons x y m a
map_S = mkElement_S "map"
map_T = mkElement_T "map"
menu   = mkElement   "menu"
menu, menu_S, menu_T :: Monad m => HTMLCons x y m a
menu_S = mkElement_S "menu"
menu_T = mkElement_T "menu"
meta   = mkEmpty   "meta"
meta, meta_S, meta_T :: Monad m => HTMLCons x y m a
meta_S = mkEmpty_S "meta"
meta_T = mkEmpty_T "meta"
noframes   = mkElement   "noframes"
noframes, noframes_S, noframes_T :: Monad m => HTMLCons x y m a
noframes_S = mkElement_S "noframes"
noframes_T = mkElement_T "noframes"
noscript   = mkElement   "noscript"
noscript, noscript_S, noscript_T :: Monad m => HTMLCons x y m a
noscript_S = mkElement_S "noscript"
noscript_T = mkElement_T "noscript"
object   = mkElement   "object"
object, object_S, object_T :: Monad m => HTMLCons x y m a
object_S = mkElement_S "object"
object_T = mkElement_T "object"
ol   = mkElement   "ol"
ol, ol_S, ol_T :: Monad m => HTMLCons x y m a
ol_S = mkElement_S "ol"
ol_T = mkElement_T "ol"
optgroup   = mkElement   "optgroup"
optgroup, optgroup_S, optgroup_T :: Monad m => HTMLCons x y m a
optgroup_S = mkElement_S "optgroup"
optgroup_T = mkElement_T "optgroup"
option   = mkElement   "option"
option, option_S, option_T :: Monad m => HTMLCons x y m a
option_S = mkElement_S "option"
option_T = mkElement_T "option"
p   = mkElement   "p"
p, p_S, p_T :: Monad m => HTMLCons x y m a
p_S = mkElement_S "p"
p_T = mkElement_T "p"
param   = mkEmpty   "param"
param, param_S, param_T :: Monad m => HTMLCons x y m a
param_S = mkEmpty_S "param"
param_T = mkEmpty_T "param"
pre   = mkElement   "pre"
pre, pre_S, pre_T :: Monad m => HTMLCons x y m a
pre_S = mkElement_S "pre"
pre_T = mkElement_T "pre"
q   = mkElement   "q"
q, q_S, q_T :: Monad m => HTMLCons x y m a
q_S = mkElement_S "q"
q_T = mkElement_T "q"
s   = mkElement   "s"
s, s_S, s_T :: Monad m => HTMLCons x y m a
s_S = mkElement_S "s"
s_T = mkElement_T "s"
samp   = mkElement   "samp"
samp, samp_S, samp_T :: Monad m => HTMLCons x y m a
samp_S = mkElement_S "samp"
samp_T = mkElement_T "samp"
script   = mkElement   "script"
script, script_S, script_T :: Monad m => HTMLCons x y m a
script_S = mkElement_S "script"
script_T = mkElement_T "script"
select   = mkElement   "select"
select, select_S, select_T :: Monad m => HTMLCons x y m a
select_S = mkElement_S "select"
select_T = mkElement_T "select"
small   = mkElement   "small"
small, small_S, small_T :: Monad m => HTMLCons x y m a
small_S = mkElement_S "small"
small_T = mkElement_T "small"
span   = mkElement   "span"
span, span_S, span_T :: Monad m => HTMLCons x y m a
span_S = mkElement_S "span"
span_T = mkElement_T "span"
strike   = mkElement   "strike"
strike, strike_S, strike_T :: Monad m => HTMLCons x y m a
strike_S = mkElement_S "strike"
strike_T = mkElement_T "strike"
strong   = mkElement   "strong"
strong, strong_S, strong_T :: Monad m => HTMLCons x y m a
strong_S = mkElement_S "strong"
strong_T = mkElement_T "strong"
style   = mkElement   "style"
style, style_S, style_T :: Monad m => HTMLCons x y m a
style_S = mkElement_S "style"
style_T = mkElement_T "style"
sub   = mkElement   "sub"
sub, sub_S, sub_T :: Monad m => HTMLCons x y m a
sub_S = mkElement_S "sub"
sub_T = mkElement_T "sub"
sup   = mkElement   "sup"
sup, sup_S, sup_T :: Monad m => HTMLCons x y m a
sup_S = mkElement_S "sup"
sup_T = mkElement_T "sup"
table   = mkElement   "table"
table, table_S, table_T :: Monad m => HTMLCons x y m a
table_S = mkElement_S "table"
table_T = mkElement_T "table"
tbody   = mkElement   "tbody"
tbody, tbody_S, tbody_T :: Monad m => HTMLCons x y m a
tbody_S = mkElement_S "tbody"
tbody_T = mkElement_T "tbody"
td   = mkElement   "td"
td, td_S, td_T :: Monad m => HTMLCons x y m a
td_S = mkElement_S "td"
td_T = mkElement_T "td"
textarea   = mkElement   "textarea"
textarea, textarea_S, textarea_T :: Monad m => HTMLCons x y m a
textarea_S = mkElement_S "textarea"
textarea_T = mkElement_T "textarea"
tfoot   = mkElement   "tfoot"
tfoot, tfoot_S, tfoot_T :: Monad m => HTMLCons x y m a
tfoot_S = mkElement_S "tfoot"
tfoot_T = mkElement_T "tfoot"
th   = mkElement   "th"
th, th_S, th_T :: Monad m => HTMLCons x y m a
th_S = mkElement_S "th"
th_T = mkElement_T "th"
thead   = mkElement   "thead"
thead, thead_S, thead_T :: Monad m => HTMLCons x y m a
thead_S = mkElement_S "thead"
thead_T = mkElement_T "thead"
title   = mkElement   "title"
title, title_S, title_T :: Monad m => HTMLCons x y m a
title_S = mkElement_S "title"
title_T = mkElement_T "title"
tr   = mkElement   "tr"
tr, tr_S, tr_T :: Monad m => HTMLCons x y m a
tr_S = mkElement_S "tr"
tr_T = mkElement_T "tr"
tt   = mkElement   "tt"
tt, tt_S, tt_T :: Monad m => HTMLCons x y m a
tt_S = mkElement_S "tt"
tt_T = mkElement_T "tt"
u   = mkElement   "u"
u, u_S, u_T :: Monad m => HTMLCons x y m a
u_S = mkElement_S "u"
u_T = mkElement_T "u"
ul   = mkElement   "ul"
ul, ul_S, ul_T :: Monad m => HTMLCons x y m a
ul_S = mkElement_S "ul"
ul_T = mkElement_T "ul"
var   = mkElement   "var"
var, var_S, var_T :: Monad m => HTMLCons x y m a
var_S = mkElement_S "var"
var_T = mkElement_T "var"
